# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_category',
            new_name='image_categorys',
        ),
    ]
