# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_remove_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=9, upload_to='welcome/'),
            preserve_default=False,
        ),
    ]
